
import { Factor, Characteristic, AcademicProgram } from "./types";

export const PROGRAMS: AcademicProgram[] = [
  { id: "Música Instrumental", name: "Música Instrumental" },
  { id: "Dirección de Banda", name: "Dirección de Banda" },
  { id: "Licenciatura en Música", name: "Licenciatura en Música" },
];

export const FACTORS: Factor[] = [
  { id: 1, name: "Proyecto educativo del programa", characteristics: ["C1", "C2"] },
  { id: 2, name: "Comunidad de estudiantes", characteristics: ["C3", "C4", "C5", "C6", "C7"] },
  { id: 3, name: "Comunidad de profesores", characteristics: ["C8", "C9", "C10", "C11", "C12", "C13", "C14"] },
  { id: 4, name: "Comunidad de egresados", characteristics: ["C15", "C16"] },
  { id: 5, name: "Aspectos académicos y de formación", characteristics: ["C17", "C18", "C19", "C20", "C21"] },
  { id: 6, name: "Permanencia y graduación", characteristics: ["C22", "C23", "C24", "C25"] },
  { id: 7, name: "Interacción con el entorno", characteristics: ["C26", "C27", "C28", "C29"] },
  { id: 8, name: "Investigación, creación e innovación", characteristics: ["C30", "C31", "C32", "C33", "C34", "C35"] },
  { id: 9, name: "Bienestar de la comunidad académica", characteristics: ["C36", "C37", "C38"] },
  { id: 10, name: "Medios educativos y ambientes de aprendizaje", characteristics: ["C39", "C40", "C41", "C42"] },
  { id: 11, name: "Organización, administración y recursos", characteristics: ["C43", "C44", "C45", "C46", "C47", "C48"] },
  { id: 12, name: "Aseguramiento de la alta calidad del programa", characteristics: ["C49", "C50", "C51"] },
];

export const CHARACTERISTICS: Characteristic[] = [
  { id: "C1", factorId: 1, name: "Coherencia del proyecto educativo", description: "Grado de correspondencia entre la misión y visión institucional y el proyecto educativo del programa.", examples: ["PEI", "Plan de estudios", "Actas de consejo"] },
  { id: "C2", factorId: 1, name: "Relevancia académica y pertinencia social", description: "Impacto del programa en la sociedad y su vigencia en el campo del conocimiento.", examples: ["Estudios de mercado", "Convenios institucionales"] },
  { id: "C3", factorId: 2, name: "Participación de los estudiantes", description: "Involucramiento de los estudiantes en órganos de gobierno y procesos académicos.", examples: ["Actas de consejo estudiantil", "Representaciones"] },
  { id: "C4", factorId: 2, name: "Orientación, acompañamiento y seguimiento", description: "Estrategias de tutoría y apoyo al estudiante durante su trayectoria.", examples: ["Programas de tutorías", "Bienestar universitario"] },
  { id: "C5", factorId: 2, name: "Estrategias pedagógicas (autonomía y trabajo)", description: "Métodos que fomentan el aprendizaje autónomo y el trabajo colaborativo.", examples: ["Guías de cátedra", "Metodologías de clase"] },
  { id: "C6", factorId: 2, name: "Políticas académicas y normativas (inclusión y diversidad)", description: "Normas que garantizan el acceso y permanencia sin discriminación.", examples: ["Protocolos de inclusión", "Reglamento estudiantil"] },
  { id: "C7", factorId: 2, name: "Estímulos y apoyos a estudiantes", description: "Apoyos financieros, becas y reconocimientos para el bienestar estudiantil.", examples: ["Becas", "Auxilios", "Monitorías"] },
  { id: "C8", factorId: 3, name: "Resultados de selección, vinculación y permanencia", description: "Transparencia y efectividad en la contratación y estabilidad del personal.", examples: ["Convocatorias", "Contratos", "Evaluaciones"] },
  { id: "C9", factorId: 3, name: "Estatuto, trayectoria y reconocimiento", description: "Evolución y méritos de la planta profesoral.", examples: ["Hoja de vida docente", "Premios", "Certificados"] },
  { id: "C10", factorId: 3, name: "Planta profesoral (desarrollo del proyecto educativo)", description: "Suficiencia e idoneidad de los docentes para cumplir el PEP.", examples: ["Carga académica", "Perfiles docentes"] },
  { id: "C11", factorId: 3, name: "Desarrollo profesoral (capacidades y resultados)", description: "Capacitación y formación continua de los docentes.", examples: ["Diplomados", "Postgrados", "Certificados"] },
  { id: "C12", factorId: 3, name: "Coherencia de estímulos en trayectoria docente", description: "Relación entre el desempeño y los incentivos recibidos.", examples: ["Bonificaciones", "Ascensos"] },
  { id: "C13", factorId: 3, name: "Producción, permanencia y evaluación profesoral", description: "Investigación y estabilidad en el tiempo.", examples: ["Publicaciones", "Obras artísticas"] },
  { id: "C14", factorId: 3, name: "Evaluación integral de profesores", description: "Procesos periódicos de retroalimentación docente.", examples: ["Encuestas a estudiantes", "Pares"] },
  { id: "C15", factorId: 4, name: "Seguimiento, caracterización y aportes de egresados", description: "Gestión de información sobre los profesionales graduados.", examples: ["Base de datos egresados", "Encuestas de empleo"] },
  { id: "C16", factorId: 4, name: "Impacto y reconocimientos de egresados", description: "Logros alcanzados por los graduados en el ámbito profesional.", examples: ["Premios de egresados", "Cargos importantes"] },
  { id: "C17", factorId: 5, name: "Evaluación de la gestión curricular", description: "Procesos de revisión y actualización del currículo.", examples: ["Actas de comité de currículo"] },
  { id: "C18", factorId: 5, name: "Coherencia de estrategias pedagógicas", description: "Alineación entre métodos de enseñanza y objetivos de formación.", examples: ["Revisiones de sílabos"] },
  { id: "C19", factorId: 5, name: "Sistemas de evaluación del aprendizaje", description: "Transparencia y efectividad en la calificación.", examples: ["Rúbricas", "Exámenes"] },
  { id: "C20", factorId: 5, name: "Aportes del sistema de evaluación", description: "Cómo la evaluación mejora el proceso educativo.", examples: ["Informes de desempeño"] },
  { id: "C21", factorId: 5, name: "Coherencia entre resultados y objetivos", description: "Verificación de que se cumple lo prometido en el perfil de egreso.", examples: ["Saber Pro", "Proyectos de grado"] },
  { id: "C22", factorId: 6, name: "Impacto de políticas de permanencia y graduación", description: "Efectividad de las medidas para evitar la deserción.", examples: ["Estadísticas de retención"] },
  { id: "C23", factorId: 6, name: "Caracterización y atención a estudiantes", description: "Conocimiento de la población estudiantil.", examples: ["Perfiles socioeconómicos"] },
  { id: "C24", factorId: 6, name: "Resultados de programas de acompañamiento", description: "Logros de las tutorías y monitorías.", examples: ["Reportes PAME"] },
  { id: "C25", factorId: 6, name: "Reducción de deserción y graduación oportuna", description: "Metas cumplidas en tiempos de graduación.", examples: ["Tasas de graduación"] },
  { id: "C26", factorId: 7, name: "Inserción del programa en contextos", description: "Presencia del programa en el ámbito local y regional.", examples: ["Convenios", "Alianzas"] },
  { id: "C27", factorId: 7, name: "Resultados de cooperación e interacción", description: "Logros derivados de convenios.", examples: ["Certificados de cumplimiento"] },
  { id: "C28", factorId: 7, name: "Efectos de políticas en contextos culturales", description: "Impacto artístico y cultural del programa.", examples: ["Programas de conciertos públicos"] },
  { id: "C29", factorId: 7, name: "Impacto de proyección social", description: "Contribución del programa a la comunidad externa.", examples: ["Proyectos de extensión"] },
  { id: "C30", factorId: 8, name: "Capacidades y procesos de investigación", description: "Infraestructura y semilleros de investigación.", examples: ["Grupos de investigación", "Líneas"] },
  { id: "C31", factorId: 8, name: "Resultados e impactos de investigación", description: "Publicaciones y creaciones artísticas.", examples: ["Artículos", "CDs", "Partituras"] },
  { id: "C32", factorId: 8, name: "Coherencia de líneas de investigación", description: "Relación entre investigación y docencia.", examples: ["Documentos de grupos"] },
  { id: "C33", factorId: 8, name: "Resultados de formación investigativa", description: "Involucramiento de estudiantes en investigación.", examples: ["Tesis", "Semilleros"] },
  { id: "C34", factorId: 8, name: "Demostración de resultados en investigación", description: "Evidencias tangibles de producción académica.", examples: ["Minciencias", "Patentes"] },
  { id: "C35", factorId: 8, name: "Impacto de investigación en el contexto", description: "Cómo la investigación soluciona problemas reales.", examples: ["Citas", "Transferencia"] },
  { id: "C36", factorId: 9, name: "Evaluación de programas de bienestar", description: "Uso y satisfacción con servicios de bienestar.", examples: ["Encuestas de satisfacción"] },
  { id: "C37", factorId: 9, name: "Incidencia del bienestar en la calidad de vida", description: "Impacto de la salud y cultura en la comunidad.", examples: ["Estadísticas de salud"] },
  { id: "C38", factorId: 9, name: "Adaptación y evaluación de infraestructura de bienestar", description: "Calidad de los espacios físicos de bienestar.", examples: ["Mantenimientos", "Aforos"] },
  { id: "C39", factorId: 10, name: "Evolución de medios educativos", description: "Actualización de bibliotecas y laboratorios.", examples: ["Inventarios", "Compras"] },
  { id: "C40", factorId: 10, name: "Aporte de medios educativos al aprendizaje", description: "Cómo las TIC facilitan la enseñanza.", examples: ["Plataformas virtuales"] },
  { id: "C41", factorId: 10, name: "Suficiencia de recursos bibliográficos y TIC", description: "Cantidad y calidad de libros y bases de datos.", examples: ["Suscripciones a revistas"] },
  { id: "C42", factorId: 10, name: "Evaluación de recursos de aprendizaje", description: "Opinión de la comunidad sobre los medios educativos.", examples: ["Informes de gestión biblioteca"] },
  { id: "C43", factorId: 11, name: "Logros y resultados de la gestión organizacional", description: "Eficacia de la administración del programa.", examples: ["Planes de acción", "Informes"] },
  { id: "C44", factorId: 11, name: "Sostenibilidad y recursos del programa", description: "Gestión de presupuestos y autogestión.", examples: ["Presupuestos ejecutados"] },
  { id: "C45", factorId: 11, name: "Liderazgo en la dirección y gestión", description: "Idoneidad de los coordinadores y directores.", examples: ["Evaluaciones de directivos"] },
  { id: "C46", factorId: 11, name: "Sistemas de comunicación e información", description: "Efectividad de la difusión interna y externa.", examples: ["Redes sociales", "Página web"] },
  { id: "C47", factorId: 11, name: "Consolidación de recursos y capacidades", description: "Fortalecimiento institucional.", examples: ["Certificaciones"] },
  { id: "C48", factorId: 11, name: "Sostenibilidad financiera del programa", description: "Viabilidad a largo plazo.", examples: ["Estados financieros"] },
  { id: "C49", factorId: 12, name: "Reflexión y autorregulación del programa", description: "Cultura de la autoevaluación constante.", examples: ["Actas de autoevaluación"] },
  { id: "C50", factorId: 12, name: "Consolidación de la información", description: "Orden y veracidad de los datos recogidos.", examples: ["Informes integrados"] },
  { id: "C51", factorId: 12, name: "Fortalecimiento del sistema de calidad", description: "Mejoras implementadas tras autoevaluación.", examples: ["Plan de mejoramiento"] },
];

export const EVIDENCE_TYPES = [
  "Concierto",
  "Recital",
  "Clase magistral",
  "Congreso",
  "Evento internacional",
  "Investigación",
  "Extensión",
  "Egreso",
  "Docencia",
  "Acta",
  "Informe",
  "Reunión",
  "Flyer",
  "Certificado",
  "Fotografía",
  "Convenio",
  "Otro",
];
